matrix:
  include:
    - language: python
      python:
        - 3.3
      install:
        - pip install -r requirements.txt
        - pip install -r requirements.dev.txt
      script:
        - make lint
        - make docs

    - language: python
      python:
        - 3.6
      install:
        - pip install -r requirements.txt
        - pip install -r requirements.dev.txt
      script:
        - make lint
        - make docs

    - language: node_js
      node_js:
        - node
        - 7
      install:
        - make -C app/admin/ui dist
      before_script:
        - cd app/admin/ui
      script:
        - npm run build
        - npm run lint
